version: '2'

services:

  db:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker

  web:
    build: .
    user: root
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    links:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  tests:
    build: .
    user: root
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    links:
      - db
    command: py.test -s --cov=. --cov-report=html



